-- =============================================================================
-- V2 seller category assignment
-- =============================================================================
--
-- 1. `seller_categories` — the MASTER categories (shared taxonomy roots) admin
--    has assigned to a seller (schema.prisma: SellerCategory). A seller may
--    create products and its own subcategories only under its assigned
--    master categories. Generated by `prisma migrate diff` from the schema
--    change. Additive: no existing table or column changes.
--
-- 2. Backfill (hand-written): every existing non-restaurant seller is
--    assigned the master category of every product it already lists or has
--    submitted, so no current seller loses access to its own catalogue when
--    the rule starts being enforced. The master category is the shared root
--    whose `path` is the first segment of the product category's path
--    (e.g. "grocery/atta-rice-dal" -> "grocery"). Restaurants are skipped:
--    their menu sections are their own root categories and stay governed by
--    catalog/category-scope.ts. Idempotent (ON CONFLICT DO NOTHING).
-- =============================================================================

BEGIN;

-- (generated) CreateTable
CREATE TABLE "seller_categories" (
    "id" UUID NOT NULL,
    "seller_id" UUID NOT NULL,
    "category_id" UUID NOT NULL,
    "assigned_by_user_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "seller_categories_pkey" PRIMARY KEY ("id")
);

-- (generated) CreateIndex
CREATE INDEX "seller_categories_category_id_idx" ON "seller_categories"("category_id");

-- (generated) CreateIndex
CREATE UNIQUE INDEX "seller_categories_seller_id_category_id_key" ON "seller_categories"("seller_id", "category_id");

-- (generated) AddForeignKey
ALTER TABLE "seller_categories" ADD CONSTRAINT "seller_categories_seller_id_fkey" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- (generated) AddForeignKey
ALTER TABLE "seller_categories" ADD CONSTRAINT "seller_categories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- (hand-written) Backfill from each seller's existing catalogue.
INSERT INTO "seller_categories" ("id", "seller_id", "category_id")
SELECT gen_random_uuid(), used.seller_id, root.id
FROM (
    SELECT sl.seller_id, p.category_id
    FROM "seller_listings" sl
    JOIN "product_variants" v ON v.id = sl.variant_id
    JOIN "products" p ON p.id = v.product_id
    UNION
    SELECT p.submitted_by_seller_id, p.category_id
    FROM "products" p
    WHERE p.submitted_by_seller_id IS NOT NULL AND p.deleted_at IS NULL
) used
JOIN "sellers" s ON s.id = used.seller_id
  AND s.seller_type <> 'RESTAURANT'
  AND s.deleted_at IS NULL
JOIN "categories" c ON c.id = used.category_id
JOIN "categories" root ON root.path = split_part(c.path, '/', 1)
  AND root.parent_id IS NULL
  AND root.seller_id IS NULL
  AND root.deleted_at IS NULL
GROUP BY used.seller_id, root.id
ON CONFLICT ("seller_id", "category_id") DO NOTHING;

COMMIT;
