-- =============================================================================
-- V2 seller availability switch + commission rule scope
-- =============================================================================
--
-- 1. `sellers.is_accepting_orders` — the seller's own Store Open / Store
--    Closed switch (schema.prisma: Seller.isAcceptingOrders). Separate from
--    the admin-controlled `is_active`. DEFAULT true: every existing seller
--    keeps exactly its current behaviour (all of them are orderable today).
--    Generated by `prisma migrate diff` from the schema change.
--
-- 2. `commission_rules_single_scope` — a rule is scoped to EITHER a product
--    OR a category, never both and never neither. Commission resolution
--    (commission.service.ts) treats any active row with a matching
--    `category_id` as a category rule and any with a matching `product_id` as
--    a product rule, so a row carrying both would resolve differently in the
--    single and batched resolvers; a row with neither is meaningless (the
--    seller default lives on `sellers.default_commission_bp`). Hand-written:
--    Prisma cannot express CHECK constraints. The table is empty in V2 dev.
-- =============================================================================

BEGIN;

-- (generated) AlterTable
ALTER TABLE "sellers" ADD COLUMN     "is_accepting_orders" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "commission_rules"
  ADD CONSTRAINT "commission_rules_single_scope"
    CHECK (("category_id" IS NULL) <> ("product_id" IS NULL));

COMMIT;
