/**
 * PRIVATE document storage — seller onboarding PDFs (PAN, Aadhaar, GST, …).
 *
 * Unlike product images (index.ts), nothing here is ever public:
 *   - local: files live under `storage-private/`, which is NOT the folder the
 *     /static route serves (`storage/`), so there is no URL that reaches them;
 *   - s3:    a separate PRIVATE bucket (S3_PRIVATE_BUCKET), accessed with
 *     short-lived SigV4 requests made by the server itself.
 * The only way to read a document is through the authorised API endpoints,
 * which stream the bytes after checking who is asking.
 *
 * Keys are generated by the server (`buildDocumentKey`) — never taken from a
 * client — and every local path is resolved and checked to stay inside the
 * private root, so a malformed key can never traverse out of it.
 */

import { randomUUID } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { env } from '../../config/env';
import { AppError } from '../../common/errors';
import { ErrorCode } from '../../shared';
import { presignS3 } from './index';

export interface PrivateDocumentStore {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
}

/** Server-generated key: `seller-documents/<sellerId>/<uuid>.pdf`. */
export function buildDocumentKey(sellerId: string): string {
  if (!/^[0-9a-f-]{36}$/i.test(sellerId)) throw new Error('invalid seller id for a document key');
  return `seller-documents/${sellerId}/${randomUUID()}.pdf`;
}

const KEY_PATTERN = /^seller-documents\/[0-9a-f-]{36}\/[0-9a-f-]{36}\.pdf$/i;

function assertDocumentKey(key: string): void {
  if (!KEY_PATTERN.test(key)) {
    throw new AppError(ErrorCode.NOT_FOUND, { message: 'Document not found.', internalMessage: 'malformed document key' });
  }
}

class LocalPrivateDocumentStore implements PrivateDocumentStore {
  readonly name = 'local';
  private readonly root = path.resolve(process.cwd(), 'storage-private');

  private resolve(key: string): string {
    assertDocumentKey(key);
    const target = path.resolve(this.root, key);
    if (!target.startsWith(this.root + path.sep)) {
      throw new AppError(ErrorCode.NOT_FOUND, { message: 'Document not found.', internalMessage: 'document path escaped root' });
    }
    return target;
  }

  async put(key: string, body: Buffer): Promise<void> {
    const target = this.resolve(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, body, { flag: 'wx' });
  }

  async get(key: string): Promise<Buffer> {
    try {
      return await readFile(this.resolve(key));
    } catch (error) {
      if (error instanceof AppError) throw error;
      throw new AppError(ErrorCode.NOT_FOUND, { message: 'Document file not found.', internalMessage: 'document file missing on disk' });
    }
  }

  async remove(key: string): Promise<void> {
    await unlink(this.resolve(key)).catch(() => undefined);
  }
}

class S3PrivateDocumentStore implements PrivateDocumentStore {
  readonly name = 's3';

  private bucket(): string {
    if (!env.S3_PRIVATE_BUCKET) {
      throw new AppError(ErrorCode.INTERNAL_ERROR, {
        message: 'Document uploads are not configured yet.',
        internalMessage: 'S3_PRIVATE_BUCKET is required for seller documents when STORAGE_PROVIDER=s3',
      });
    }
    return env.S3_PRIVATE_BUCKET;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    assertDocumentKey(key);
    const response = await fetch(presignS3('PUT', this.bucket(), key, contentType, 300), {
      method: 'PUT',
      body: new Uint8Array(body),
      headers: { 'Content-Type': contentType },
    });
    if (!response.ok) {
      throw new AppError(ErrorCode.INTERNAL_ERROR, { internalMessage: `private document upload failed: ${response.status}` });
    }
  }

  async get(key: string): Promise<Buffer> {
    assertDocumentKey(key);
    const response = await fetch(presignS3('GET', this.bucket(), key, undefined, 120));
    if (response.status === 404) {
      throw new AppError(ErrorCode.NOT_FOUND, { message: 'Document file not found.' });
    }
    if (!response.ok) {
      throw new AppError(ErrorCode.INTERNAL_ERROR, { internalMessage: `private document read failed: ${response.status}` });
    }
    return Buffer.from(await response.arrayBuffer());
  }

  async remove(key: string): Promise<void> {
    assertDocumentKey(key);
    await fetch(presignS3('DELETE', this.bucket(), key, undefined, 120), { method: 'DELETE' }).catch(() => undefined);
  }
}

export const privateDocuments: PrivateDocumentStore =
  env.STORAGE_PROVIDER === 's3' ? new S3PrivateDocumentStore() : new LocalPrivateDocumentStore();
